bind = SUPER, Return, exec, alacritty
bind = SUPER, Q, killactive
bind = SUPER, D, exec, rofi -show drun
bind = SUPER, F, fullscreen
bind = SUPER, V, togglefloating  
bind = SUPER, P, pseudo          
bind = SUPER, E, exec, nautilus
bind = SUPER, C, centerwindow

# Переключение рабочего стола
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, left, workspace, -1
bind = SUPER, right, workspace, +1

# Перемещение окон между рабочими столами
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5

# УПРАВЛЕНИЕ ОКНАМИ НА ОДНОМ РАБОЧЕМ СТОЛЕ
# Перемещение окон стрелками
bind = SUPER SHIFT, left, movewindow, l
bind = SUPER SHIFT, right, movewindow, r
bind = SUPER SHIFT, up, movewindow, u
bind = SUPER SHIFT, down, movewindow, d

# Изменение размера окон
bind = SUPER CTRL, left, resizeactive, -20 0
bind = SUPER CTRL, right, resizeactive, 20 0
bind = SUPER CTRL, up, resizeactive, 0 -20
bind = SUPER CTRL, down, resizeactive, 0 20

# Управление фокусом между окнами
bind = SUPER, left, focuswindow, l
bind = SUPER, right, focuswindow, r
bind = SUPER, up, focuswindow, u
bind = SUPER, down, focuswindow, d

# Управление звуком
bind = , XF86AudioRaiseVolume, exec, pamixer -i 5
bind = , XF86AudioLowerVolume, exec, pamixer -d 5
bind = , XF86AudioMute, exec, pamixer -t

# Скриншоты
#bind = , Print, exec, grim -g "$(slurp)" - | wl-copy
#bind = SHIFT, Print, exec, grim -g "$(slurp)" ~/Pictures/Screenshot-$(date +%Y%m%d-%H%M%S).png

# Завершение работы Hyprland
bind = SUPER SHIFT, E, exec, wlogout

