
# NVIDIA
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

#env = http_proxy,http://127.0.0.1:1081
#env = https_proxy,http://127.0.0.1:1081
#env = socks_proxy,socks://127.0.0.1:1080
#env = ALL_PROXY,socks://127.0.0.1:1080